
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COR_A COR_C DPTOS COMA PAQUETE DATOS EJECUCION MENSAJE HISTORIAL CADENAplycs : COR_A PAQUETE  DPTOS CADENA COMA DATOS DPTOS CADENA COMA EJECUCION  DPTOS CADENA COMA MENSAJE  DPTOS CADENA COMA HISTORIAL  DPTOS CADENA COR_C'
    
_lr_action_items = {'COR_A':([0,],[2,]),'$end':([1,22,],[0,-1,]),'PAQUETE':([2,],[3,]),'DPTOS':([3,7,11,15,19,],[4,8,12,16,20,]),'CADENA':([4,8,12,16,20,],[5,9,13,17,21,]),'COMA':([5,9,13,17,],[6,10,14,18,]),'DATOS':([6,],[7,]),'EJECUCION':([10,],[11,]),'MENSAJE':([14,],[15,]),'HISTORIAL':([18,],[19,]),'COR_C':([21,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'plycs':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> plycs","S'",1,None,None,None),
  ('plycs -> COR_A PAQUETE DPTOS CADENA COMA DATOS DPTOS CADENA COMA EJECUCION DPTOS CADENA COMA MENSAJE DPTOS CADENA COMA HISTORIAL DPTOS CADENA COR_C','plycs',21,'p_plycs','analisis_sintactico.py',10),
]
