
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COR_A COR_C DPTOS LOGIN USR CADENAplycs : COR_A LOGIN DPTOS CADENA USR DPTOS CADENA  COR_C'
    
_lr_action_items = {'COR_A':([0,],[2,]),'$end':([1,9,],[0,-1,]),'LOGIN':([2,],[3,]),'DPTOS':([3,6,],[4,7,]),'CADENA':([4,7,],[5,8,]),'USR':([5,],[6,]),'COR_C':([8,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'plycs':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> plycs","S'",1,None,None,None),
  ('plycs -> COR_A LOGIN DPTOS CADENA USR DPTOS CADENA COR_C','plycs',8,'p_plycs','analisis_sintactico_usr.py',10),
]
